apiVersion: v1
kind: Pod
metadata:
  name: test-pull
  namespace: kubeflow
spec:
  containers:
  - name: test
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/kubeflowkatib/pytorch-mnist-cpu:v0.16.0
    command: ["sleep", "3600"]
  restartPolicy: Never
